-- 1. Create the Books Table
CREATE TABLE books (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  description TEXT,
  image_url TEXT, -- URL to the book cover
  buy_url TEXT,   -- Link to Amazon/Flipkart/Govt Site (Can be NULL)
  category TEXT DEFAULT 'General' -- Beginner, Investing, Psychology
);

-- 2. Insert Recommended Books (Real Links)
INSERT INTO books (title, author, description, image_url, buy_url, category) VALUES
(
  'The Psychology of Money', 
  'Morgan Housel', 
  'Timeless lessons on wealth, greed, and happiness. A must-read for beginners.', 
  'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UF1000,1000_QL80_.jpg', 
  'https://www.amazon.in/Psychology-Money-Morgan-Housel/dp/9390166268',
  'Psychology'
),
(
  'Rich Dad Poor Dad', 
  'Robert Kiyosaki', 
  'The #1 Personal Finance book of all time. Explains assets vs liabilities clearly.', 
  'https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg', 
  'https://www.amazon.in/Rich-Dad-Poor-Middle-Updates/dp/1612680194',
  'Beginner'
),
(
  'Lets Talk Money', 
  'Monika Halan', 
  'India’s best personal finance book. Tailored specifically for the Indian market.', 
  'https://m.media-amazon.com/images/I/71+qM6+I9dL._AC_UF1000,1000_QL80_.jpg', 
  'https://www.amazon.in/Lets-Talk-Money-Monika-Halan/dp/9352779384',
  'Indian Finance'
),
(
  'RBI Financial Education', 
  'Reserve Bank of India', 
  'Official financial literacy guide by the Govt of India. Free and authentic.', 
  'https://rbidocs.rbi.org.in/rdocs/content/images/FEP10092016_1.jpg', 
  'https://rbi.org.in/FinancialEducation/',
  'Government'
),
(
  'The Intelligent Investor', 
  'Benjamin Graham', 
  'The classic text on value investing. Recommended by Warren Buffett.', 
  'https://m.media-amazon.com/images/I/91+t0Di07FL._AC_UF1000,1000_QL80_.jpg', 
  NULL, -- NULL means "Not available online" (Simulated for this example)
  'Investing'
);
