-- ========================================================
-- 1. FIX SCHEMA ISSUES (Run this once)
-- ========================================================

-- MODULES TABLE FIXES
ALTER TABLE public.modules 
ADD COLUMN IF NOT EXISTS icon TEXT,
ADD COLUMN IF NOT EXISTS color TEXT,
ADD COLUMN IF NOT EXISTS description TEXT;

-- LESSONS TABLE FIXES
ALTER TABLE public.lessons 
ADD COLUMN IF NOT EXISTS duration INTEGER DEFAULT 5;

-- CARDS TABLE FIXES
-- We use ALTER TABLE because the table likely exists but is missing columns
ALTER TABLE public.cards 
ADD COLUMN IF NOT EXISTS content TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'concept',
ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;

-- Ensure 'cards' table exists with correct structure (BIGINT now)
CREATE TABLE IF NOT EXISTS public.cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- 2. INSERT CONTENT (Modules 4, 5, 6)
-- ========================================================
DO $$
DECLARE
  -- Changed types from UUID to BIGINT to match database schema (based on error "17")
  v_mod4_id BIGINT;
  v_mod5_id BIGINT;
  v_mod6_id BIGINT;
  v_lesson_id BIGINT;
BEGIN

  -- ----------------------------------------------------
  -- GET OR CREATE MODULE IDs
  -- ----------------------------------------------------
  
  -- Module 4: Investing Foundations
  SELECT id INTO v_mod4_id FROM public.modules WHERE title = 'Investing Foundations';
  IF v_mod4_id IS NULL THEN
    INSERT INTO public.modules (title, description, order_index, icon, color) 
    VALUES ('Investing Foundations', 'From Knowing → To Structured Thinking', 4, 'TrendingUp', 'bg-blue-600') 
    RETURNING id INTO v_mod4_id;
  END IF;

  -- Module 5: SIP & Mutual Funds
  SELECT id INTO v_mod5_id FROM public.modules WHERE title = 'SIP & Mutual Funds';
  IF v_mod5_id IS NULL THEN
    INSERT INTO public.modules (title, description, order_index, icon, color) 
    VALUES ('SIP & Mutual Funds', 'Systematic Wealth Building', 5, 'PieChart', 'bg-green-600') 
    RETURNING id INTO v_mod5_id;
  END IF;

  -- Module 6: Understanding Stocks
  SELECT id INTO v_mod6_id FROM public.modules WHERE title = 'Understanding Stocks';
  IF v_mod6_id IS NULL THEN
    INSERT INTO public.modules (title, description, order_index, icon, color) 
    VALUES ('Understanding Stocks', 'Ownership & Analysis', 6, 'BarChart', 'bg-purple-600') 
    RETURNING id INTO v_mod6_id;
  END IF;

  -- CLEAR OLD DATA FOR THESE MODULES (Prevents duplicates if re-run)
  -- Note: Cascading delete should handle lessons and cards if module deleted, 
  -- but here we delete lessons for specific modules to reset content.
  DELETE FROM public.lessons WHERE module_id IN (v_mod4_id, v_mod5_id, v_mod6_id);


  -- ----------------------------------------------------
  -- MODULE 4: INVESTING FOUNDATIONS
  -- ----------------------------------------------------

  -- Lesson 1
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod4_id, 'Investing vs Trading vs Speculation', 6, 1) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Many young investors enter markets expecting quick profit. The mistake is rarely the market—it is misunderstanding the game.', '{}', 1),
  (v_lesson_id, 'concept', 'Investing is for long-term growth. Trading is for short-term price movement. Speculation is betting on uncertainty.', '{"icon": "TrendingUp", "subtext": "Know the difference"}', 2),
  (v_lesson_id, 'explanation', 'Investing asks: "Is this business strong over time?" Trading asks: "Will the price move this week?"', '{}', 3),
  (v_lesson_id, 'explanation', 'Real Example: Person A invests in diversified funds for 8 years and builds stability. Person B trades daily on tips and faces emotional ups and downs.', '{}', 4),
  (v_lesson_id, 'interaction', 'Which approach is more stable for beginners?', '{"options": ["Long-term investing", "Frequent trading"], "correct_id": "Long-term investing", "answer": "Long-term investing"}', 5),
  (v_lesson_id, 'concept', 'Start as an investor. Understand patience before chasing speed.', '{"icon": "Clock", "subtext": "Patience Pays"}', 6),
  (v_lesson_id, 'quiz', 'Investing mainly focuses on:', '{"options": ["Short-term movement", "Long-term growth"], "correct_id": "Long-term growth", "answer": "Long-term growth"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 2
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod4_id, 'Time Horizon & Risk Capacity', 5, 2) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Two investors choose the same stock. One panics after 3 months, the other wins after 5 years. The difference is Time.', '{}', 1),
  (v_lesson_id, 'concept', 'Time Horizon = How long you can stay invested. Risk Tolerance = How much volatility you can emotionally handle.', '{"icon": "Activity", "subtext": "Time & Emotion"}', 2),
  (v_lesson_id, 'explanation', 'Short-term goals require stability (low risk). Long-term goals can tolerate volatility (high risk).', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: You need money in 1 year for fees. You put it in high-risk stocks. Market drops 20%. This is a time mismatch.', '{}', 4),
  (v_lesson_id, 'interaction', 'You need money in 12 months. Which is safer?', '{"options": ["High-risk equity", "Low-risk instrument"], "correct_id": "Low-risk instrument", "answer": "Low-risk instrument"}', 5),
  (v_lesson_id, 'concept', 'Match investment to time. Never invest short-term money in high volatility assets.', '{"icon": "CheckCircle", "subtext": "Match the Goal"}', 6),
  (v_lesson_id, 'quiz', 'Short-term goals require:', '{"options": ["Stability", "High volatility"], "correct_id": "Stability", "answer": "Stability"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 3
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod4_id, 'Asset Classes Explained Clearly', 6, 3) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Not all investments behave the same. Some grow fast but fluctuate. Some grow slow but steady. Mixing them is key.', '{}', 1),
  (v_lesson_id, 'concept', 'Equity = Ownership (Growth). Debt = Lending (Stability). Gold = Store of Value. Hybrid = Mix of assets.', '{"icon": "PieChart", "subtext": "The Menu"}', 2),
  (v_lesson_id, 'explanation', 'Equity offers higher growth potential but higher risk. Debt offers stability but lower growth. Diversifying balances risk.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: Putting all money in one stock is dangerous. Spreading it across asset classes reduces the impact of one loss.', '{}', 4),
  (v_lesson_id, 'interaction', 'Which strategy reduces risk?', '{"options": ["One asset", "Diversification"], "correct_id": "Diversification", "answer": "Diversification"}', 5),
  (v_lesson_id, 'concept', 'Understand asset behavior before investing. Balance matters more than excitement.', '{"icon": "Sliders", "subtext": "Balance"}', 6),
  (v_lesson_id, 'quiz', 'Equity represents:', '{"options": ["Ownership", "Loan only"], "correct_id": "Ownership", "answer": "Ownership"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 4
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod4_id, 'Goal-Based Investing Framework', 5, 4) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Many beginners invest without a goal. Without direction, decisions become emotional.', '{}', 1),
  (v_lesson_id, 'concept', 'Every investment decision should follow: Goal → Time → Risk → Instrument. First define purpose, then select investment.', '{"icon": "Map", "subtext": "The Framework"}', 2),
  (v_lesson_id, 'explanation', 'Short goal (1 year) → low risk. Long goal (10+ years) → growth assets. Structure prevents mistakes.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: Saving for a car in 2 years? Not suitable for high-risk speculation. Saving for retirement in 30 years? You can risks.', '{}', 4),
  (v_lesson_id, 'interaction', 'What should be defined first?', '{"options": ["Stock name", "Goal"], "correct_id": "Goal", "answer": "Goal"}', 5),
  (v_lesson_id, 'concept', 'Never choose investment before defining purpose. Purpose controls strategy.', '{"icon": "Target", "subtext": "Purpose First"}', 6),
  (v_lesson_id, 'quiz', 'Investing without a goal leads to:', '{"options": ["Structure", "Emotional decisions"], "correct_id": "Emotional decisions", "answer": "Emotional decisions"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);


  -- ----------------------------------------------------
  -- MODULE 5: SIP & MUTUAL FUNDS
  -- ----------------------------------------------------

  -- Lesson 1
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod5_id, 'What is SIP & How It Works', 6, 1) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'You don''t need a lump sum to get rich. Millions build wealth by investing small amounts consistently.', '{}', 1),
  (v_lesson_id, 'concept', 'SIP (Systematic Investment Plan) allows you to invest a fixed amount regularly. Discipline replaces timing.', '{"icon": "Repeat", "subtext": "Consistency"}', 2),
  (v_lesson_id, 'explanation', 'When markets are up, you buy less units. When down, you buy more. Over time, your average cost drops (Rupee Cost Averaging).', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: You invest ₹2,000/month for 5 years. Your habit becomes your strength, ignoring market noise.', '{}', 4),
  (v_lesson_id, 'interaction', 'What makes SIP powerful?', '{"options": ["Large one-time investment", "Regular disciplined investing"], "correct_id": "Regular disciplined investing", "answer": "Regular disciplined investing"}', 5),
  (v_lesson_id, 'concept', 'Automate your SIP. Do not pause it during temporary market falls.', '{"icon": "Settings", "subtext": "Automate It"}', 6),
  (v_lesson_id, 'quiz', 'SIP mainly builds:', '{"options": ["Discipline", "Speculation"], "correct_id": "Discipline", "answer": "Discipline"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 2
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod5_id, 'Types of Mutual Funds', 6, 2) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Not all mutual funds are the same. Choosing the wrong type can mismatch your goal.', '{}', 1),
  (v_lesson_id, 'concept', 'Equity Funds (Stocks), Debt Funds (Fixed Income), Hybrid (Mix), Index Funds (Track Market).', '{"icon": "Grid", "subtext": "Fund Types"}', 2),
  (v_lesson_id, 'explanation', 'Equity = High growth, high volatility. Debt = Stability. Index = Low cost tracking. Match the fund to your timeline.', '{}', 3),
  (v_lesson_id, 'explanation', 'For a 1-year goal, a Debt fund is safer. For a 15-year goal, an Equity fund is better.', '{}', 4),
  (v_lesson_id, 'interaction', 'Which option spreads money across many companies?', '{"options": ["Mutual fund", "Single stock"], "correct_id": "Mutual fund", "answer": "Mutual fund"}', 5),
  (v_lesson_id, 'concept', 'Choose fund type based on goal and time, not just last year''s highest return.', '{"icon": "Search", "subtext": "Look Deeper"}', 6),
  (v_lesson_id, 'quiz', 'Index funds aim to:', '{"options": ["Beat market aggressively", "Track market performance"], "correct_id": "Track market performance", "answer": "Track market performance"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 3
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod5_id, 'Power of Staying Invested', 5, 3) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Most investors lose money not because of the market, but because they exit when they are scared.', '{}', 1),
  (v_lesson_id, 'concept', 'Markets are cyclical. They rise and fall. Real wealth is made by staying invested through the dips.', '{"icon": "TrendingUp", "subtext": "Ride the Wave"}', 2),
  (v_lesson_id, 'explanation', 'Temporary declines are normal. If you sell in panic, you turn a temporary loss into a permanent one.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: An investor stops SIP during a crash. Next year markets recover 20%. They missed the recovery gain.', '{}', 4),
  (v_lesson_id, 'interaction', 'Which builds wealth better?', '{"options": ["Stopping during fall", "Continuing consistently"], "correct_id": "Continuing consistently", "answer": "Continuing consistently"}', 5),
  (v_lesson_id, 'concept', 'Volatility is the fee you pay for growth. Focus on the long-term trend, not daily noise.', '{"icon": "Eye", "subtext": "Long View"}', 6),
  (v_lesson_id, 'quiz', 'Selling in panic usually:', '{"options": ["Locks losses", "Guarantees profit"], "correct_id": "Locks losses", "answer": "Locks losses"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 4
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod5_id, 'Common SIP Mistakes', 5, 4) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Many SIPs are stopped within 2 years. The reason is rarely performance—it is impatience.', '{}', 1),
  (v_lesson_id, 'concept', 'Mistakes: Starting without a goal, stopping during downturns, expecting instant riches, ignoring emergency funds.', '{"icon": "AlertTriangle", "subtext": "Avoid These"}', 2),
  (v_lesson_id, 'explanation', 'SIP is a marathon, not a sprint. Treating it like trading leads to frustration.', '{}', 3),
  (v_lesson_id, 'interaction', 'Which mindset harms SIP most?', '{"options": ["Long-term thinking", "Short-term profit expectation"], "correct_id": "Short-term profit expectation", "answer": "Short-term profit expectation"}', 4),
  (v_lesson_id, 'concept', 'Align expectations with reality. Invest for growth, not monthly excitement.', '{"icon": "Anchor", "subtext": "Stay Grounded"}', 5),
  (v_lesson_id, 'quiz', 'Unrealistic return expectations lead to:', '{"options": ["Patience", "Early exit"], "correct_id": "Early exit", "answer": "Early exit"}', 6),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 7);


  -- ----------------------------------------------------
  -- MODULE 6: UNDERSTANDING STOCKS
  -- ----------------------------------------------------

  -- Lesson 1
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod6_id, 'Long-Term vs Short-Term', 6, 1) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Trading looks exciting and fast. Investing looks boring and slow. But "Boring" usually wins the race.', '{}', 1),
  (v_lesson_id, 'concept', 'Long-term investing focuses on business growth. Trading focuses on price movement. Speed creates excitement, Time creates wealth.', '{"icon": "Coffee", "subtext": "Boring is Good"}', 2),
  (v_lesson_id, 'explanation', 'Trading needs constant monitoring. Investing needs patience. Different effort, different mindset.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: Investor holds a solid company for 8 years. Trader flips it weekly. Investor usually builds more wealth with less stress.', '{}', 4),
  (v_lesson_id, 'interaction', 'Which is more suitable for beginners?', '{"options": ["Long-term investing", "High-frequency trading"], "correct_id": "Long-term investing", "answer": "Long-term investing"}', 5),
  (v_lesson_id, 'concept', 'If you lack time and experience, avoid short-term trading.', '{"icon": "Shield", "subtext": "Stay Safe"}', 6),
  (v_lesson_id, 'quiz', 'Trading mainly focuses on:', '{"options": ["Long-term value", "Short-term movement"], "correct_id": "Short-term movement", "answer": "Short-term movement"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 2
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod6_id, 'Diversification Basics', 5, 2) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Concentration makes you rich, but Diversification keeps you rich. Putting all eggs in one basket is risky.', '{}', 1),
  (v_lesson_id, 'concept', 'Diversification means spreading money across different sectors/companies to reduce the impact of one failure.', '{"icon": "Layers", "subtext": "Spread Risk"}', 2),
  (v_lesson_id, 'explanation', 'If one stock falls, others may rise or stay stable. This smooths out your journey.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: Tech stocks crash? Your Pharma or FMCG stocks might hold up. A balanced portfolio survives storms.', '{}', 4),
  (v_lesson_id, 'interaction', 'Diversification mainly reduces:', '{"options": ["Risk concentration", "Market existence"], "correct_id": "Risk concentration", "answer": "Risk concentration"}', 5),
  (v_lesson_id, 'concept', 'Never allocate entire capital to one company. Balance reduces emotional pressure.', '{"icon": "Minimize", "subtext": "Reduce Pressure"}', 6),
  (v_lesson_id, 'quiz', 'Concentrating in one stock increases:', '{"options": ["Stability", "Vulnerability"], "correct_id": "Vulnerability", "answer": "Vulnerability"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

  -- Lesson 3
  INSERT INTO public.lessons (module_id, title, duration, order_index) VALUES (v_mod6_id, 'Beginner Stock Mistakes', 5, 3) RETURNING id INTO v_lesson_id;
  
  INSERT INTO public.cards (lesson_id, type, content, metadata, order_index) VALUES
  (v_lesson_id, 'hook', 'Many first-time investors exit within 2 years. Not because of the market, but because of their own emotions.', '{}', 1),
  (v_lesson_id, 'concept', 'Common Mistakes: FOMO (Fear Of Missing Out), Following Tips, Panic Selling, Overconfidence.', '{"icon": "Frown", "subtext": "Emotional Traps"}', 2),
  (v_lesson_id, 'explanation', 'Buying because "everyone else is buying" usually means you are buying at the top. Panic selling locks in your loss.', '{}', 3),
  (v_lesson_id, 'explanation', 'Example: Buying a "hot stock" after it went up 50% usually ends in pain when it corrects.', '{}', 4),
  (v_lesson_id, 'interaction', 'Buying just because others are buying is:', '{"options": ["Diversification", "FOMO"], "correct_id": "FOMO", "answer": "FOMO"}', 5),
  (v_lesson_id, 'concept', 'Have a reason before buying. Have a plan before selling.', '{"icon": "Clipboard", "subtext": "Have a Plan"}', 6),
  (v_lesson_id, 'quiz', 'Panic selling usually happens due to:', '{"options": ["Discipline", "Fear"], "correct_id": "Fear", "answer": "Fear"}', 7),
  (v_lesson_id, 'reward', 'Lesson Completed!', '{"xp": 60}', 8);

END $$;
